Repository signaux-faibles/opensignauxfaibles, pull requests merged in 2020-10, with the labels that each got.

#175 fix(gournal): Renommage tracker.Error() --> tracker.Add()
  dbmongo/go.mod
  dbmongo/go.sum
  dbmongo/lib/altares/main.go
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apdemande/main.go
  dbmongo/lib/bdf/main.go
  dbmongo/lib/crp/main.go
  dbmongo/lib/diane/main.go
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/compte.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/delai.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/procol.go
Labels: dependencies, enhancement

#179 Feat/add ellisphere parser
  dbmongo/handlers.go
  dbmongo/js/RawDataTypes.ts
  dbmongo/js/common/flatten.ts
  dbmongo/js/public/map.ts
  dbmongo/js/public/public_tests.ts.md
  dbmongo/js/public/public_tests.ts.snap
  dbmongo/js/test/data/objects.js
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/engine/jsFunctions.go
  tests/input-data/RawData.sample.json.secret
  tests/output-snapshots/test-api-compact.golden.json.secret
  tests/output-snapshots/test-api-public.golden.json
Labels: enhancement

#176 fix(debits): Tolérer lignes csv incomplètes et invalides + améliorer rapports
  dbmongo/lib/base/errors.go
  dbmongo/lib/engine/main_test.go
  dbmongo/lib/marshal/filter_test.go
  dbmongo/lib/misc/main_test.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/testData/debitCorrompuTestData.csv
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  test-all.sh
  tests/output-snapshots/test-api-check.golden.txt
Labels: enhancement

#183 feat(check): L'API /data/check lit chaque fichier jusqu'à la fin
  dbmongo/lib/base/cron.go
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/main.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/urssaf/debit.go
Labels: enhancement

#188 fix(ellisphere): Refactoring du parseur "ellisphere"
  dbmongo/lib/ellisphere/main.go
Labels: enhancement

#192 fix(tests): Tri des erreurs de parsing pour reproductibilité des rapports
  dbmongo/lib/engine/main.go
Labels: bug

#191 fix(effectif): Ne pas compter les sirets invalides comme erreurs fatales
  dbmongo/lib/base/errors.go
  dbmongo/lib/marshal/filter.go
  dbmongo/lib/sfregexp/regexp.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
Labels: enhancement

#182 feat(check): L'API /data/check retourne un rapport complet pour chaque fichier parsé
  dbmongo/docs/load.go
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
  dbmongo/handlers.go
  dbmongo/lib/base/cron.go
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/event.go
  dbmongo/lib/engine/main.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/urssaf/debit.go
  tests/output-snapshots/test-api-check.golden.txt
  tests/test-api-check.sh
Labels: enhancement

#193 fix(cotisation): Compter dans le total les lignes non parsées
  dbmongo/lib/urssaf/cotisation.go
Labels: bug

#184 fix(debit): Charger les mappings de comptes URSSAF une seule fois
  dbmongo/lib/marshal/mapping.go
  dbmongo/lib/urssaf/debit.go
Labels: enhancement

#187 fix(apdemande): Refactoring du parseur "apdemande"
  dbmongo/lib/apdemande/main.go
Labels: enhancement

#189 fix(sirene): Refactoring du parseur "sirene"
  dbmongo/lib/sirene/main.go
Labels: enhancement

#197 feat: Retrait des parseurs crp et altares
  dbmongo/js/RawDataTypes.ts
  dbmongo/js/common/altaresToHuman.ts
  dbmongo/js/public/dealWithProcols.ts
  dbmongo/js/public/functions.ts
  dbmongo/js/reduce.algo2/dealWithProcols.ts
  dbmongo/js/reduce.algo2/defaillances.ts
  dbmongo/js/reduce.algo2/functions.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/lib/altares/main.go
  dbmongo/lib/crp/main.go
  dbmongo/lib/engine/jsFunctions.go
  dbmongo/lib/engine/type.go
Labels: enhancement

#196 fix(ci): Ne pas essayer de mettre à jour les paquetages
  .github/workflows/e2e.yml
  .github/workflows/go.yml
  .github/workflows/js-functions.yml
Labels: bug

#190 fix(sirene-ul): Refactoring du parseur "sirene-ul"
  dbmongo/lib/sirene_ul/main.go
Labels: enhancement

#186 fix(apconso): Refactoring du parseur "apconso"
  dbmongo/lib/apconso/main.go
Labels: enhancement

#198 fix: Harmonisation des parseurs
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apdemande/main.go
Labels: enhancement

#202 fix(parsers): Harmonisation de la forme des parseurs (suite)
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/main.go
  dbmongo/lib/engine/main_test.go
  dbmongo/lib/reporder/main_test.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/reporder/testData/expectedReporder.json
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/testData/expectedDebit.json
  dbmongo/lib/urssaf/urssaf_test.go
Labels: enhancement

#203 tests(parsers): Étendre couverture de test des parseurs
  dbmongo/lib/apconso/main_test.go
  dbmongo/lib/apconso/testData/expectedApconso.json
  dbmongo/lib/apdemande/main_test.go
  dbmongo/lib/apdemande/testData/expectedApdemande.json
  dbmongo/lib/diane/main_test.go
  dbmongo/lib/diane/testData/expectedDiane.json
  dbmongo/lib/ellisphere/main_test.go
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/marshal/testing.go
  dbmongo/lib/sirene/main_test.go
  dbmongo/lib/sirene/testData/expectedSirene.json
  dbmongo/lib/sirene_ul/main_test.go
  dbmongo/lib/sirene_ul/testData/expectedSireneUL.json
  dbmongo/lib/urssaf/testData/expectedCcsf.json
  dbmongo/lib/urssaf/testData/expectedCotisation.json
  dbmongo/lib/urssaf/testData/expectedDelai.json
  dbmongo/lib/urssaf/testData/expectedEffectif.json
  dbmongo/lib/urssaf/testData/expectedProcol.json
  dbmongo/lib/urssaf/urssaf_test.go
Labels: enhancement

#204 fix(parsers): Harmonisation des parseurs URSSAF (suite)
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/compte.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/delai.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/procol.go
  dbmongo/lib/urssaf/testData/effectifEntTestData.csv
  dbmongo/lib/urssaf/testData/expectedEffectifEnt.json
  dbmongo/lib/urssaf/urssaf_test.go
Labels: enhancement

#206 fix(parsers): Comptage des lignes traitées avec erreur
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apdemande/main.go
  dbmongo/lib/bdf/main.go
  dbmongo/lib/diane/main.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
Labels: enhancement

#201 fix(db): Ajout d'indexes sur collections
  dbmongo/lib/engine/db.go
  dbmongo/lib/engine/public.go
Labels: enhancement

#209 feat(API): Fonction "Purge" plus puissante + correction de Chunks.ToQueries()
  .github/workflows/e2e.yml
  dbmongo/docs/load.go
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
  dbmongo/handlers.go
  dbmongo/js/purgeBatch/map.js
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/data.go
  dbmongo/lib/engine/data_test.go
  dbmongo/lib/engine/jsFunctions.go
  dbmongo/lib/engine/purgeBatch.go
  dbmongo/lib/engine/reduce.go
  dbmongo/main.go
  test-all.sh
  tests/test-api-purge-batch.sh
Labels: enhancement

#208 fix(reduce): Couverture de tests pour calcul d'activité partielle (apart.ts)
  dbmongo/js/crossComputation/apart.js
  dbmongo/js/public/public_tests.ts.md
  dbmongo/js/public/public_tests.ts.snap
  dbmongo/js/reduce.algo2/apart.crossComputation.json
  dbmongo/js/reduce.algo2/apart.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/map_tests.ts.md
  dbmongo/js/reduce.algo2/map_tests.ts.snap
  dbmongo/js/test/data/objects.js
  dbmongo/lib/engine/jsFunctions.go
  dbmongo/lib/engine/reduce.go
  tests/output-snapshots/test-api-public.golden.json
  tests/output-snapshots/test-api-reduce.golden.json
Labels: enhancement

#213 tests(parsers): Inclusion de tous les parseurs dans le test d'import
  .github/workflows/e2e.yml
  dbmongo/config-sample.toml
  tests/output-snapshots/test-api-import.golden.txt
  tests/test-api-import.sh
Labels: enhancement

#207 fix(parsers): Fonction commune pour itérer sur les fichiers
  dbmongo/handlers.go
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apconso/main_test.go
  dbmongo/lib/apconso/testData/expectedApconso.json
  dbmongo/lib/apdemande/main.go
  dbmongo/lib/apdemande/main_test.go
  dbmongo/lib/apdemande/testData/expectedApdemande.json
  dbmongo/lib/bdf/main.go
  dbmongo/lib/bdf/main_test.go
  dbmongo/lib/bdf/testData/expectedBdfOutput.json
  dbmongo/lib/diane/main.go
  dbmongo/lib/diane/main_test.go
  dbmongo/lib/diane/testData/expectedDiane.json
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/ellisphere/main_test.go
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/data_test.go
  dbmongo/lib/engine/main.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/marshal/testing.go
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/reporder/main_test.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/reporder/testData/expectedReporder.json
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene/main_test.go
  dbmongo/lib/sirene/testData/expectedSirene.json
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/sirene_ul/main_test.go
  dbmongo/lib/sirene_ul/testData/expectedSireneUL.json
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/compte.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/delai.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/procol.go
  dbmongo/lib/urssaf/testData/expectedCcsf.json
  dbmongo/lib/urssaf/testData/expectedCotisation.json
  dbmongo/lib/urssaf/testData/expectedDebit.json
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  dbmongo/lib/urssaf/testData/expectedDelai.json
  dbmongo/lib/urssaf/testData/expectedEffectif.json
  dbmongo/lib/urssaf/testData/expectedEffectifEnt.json
  dbmongo/lib/urssaf/testData/expectedProcol.json
  dbmongo/lib/urssaf/urssaf_test.go
  tests/output-snapshots/test-api-check.golden.txt
  tests/output-snapshots/test-api-import.golden.txt
Labels: enhancement

#217 fix(compact): Compact n'intègre pas certains tuples dans RawData
  dbmongo/js/compact/reduce.ts
  dbmongo/js/compact/reduce_tests.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: bug

#214 fix(db): Éviter le underscore final dans le nom de collection Features_
  dbmongo/lib/engine/db.go
  dbmongo/lib/engine/reduce.go
Labels: enhancement

#218 fix(compact): Optim sur compactage d'un batch couvert par 2 documents
  dbmongo/js/compact/reduce.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: bug

#216 fix(compact): Détection d'entrée `undefined` en db pour prévenir interruption de compactage
  .github/workflows/e2e.yml
  dbmongo/js/common/forEachPopulatedProp.ts
  dbmongo/js/compact/reduce_tests.ts
  dbmongo/lib/engine/data.go
  dbmongo/lib/engine/data_validation.go
  dbmongo/validation/detect_invalid_entries.pipeline.json
  test-all.sh
  tests/test-api-compact-failure.sh
Labels: bug

#222 fix: Refonte du filtrage SIREN d'entreprises + correction Effectif
  dbmongo/lib/bdf/main.go
  dbmongo/lib/bdf/main_test.go
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/marshal/filter.go
  dbmongo/lib/marshal/filter_test.go
  dbmongo/lib/marshal/mapping.go
  dbmongo/lib/marshal/mapping_test.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/urssaf_test.go
Labels: bug, enhancement

#223 fix(filter): Retrait de IsFiltered() => validation siret/siren déléguée à l'appelant
  dbmongo/lib/bdf/main.go
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/marshal/filter.go
  dbmongo/lib/marshal/filter_test.go
  dbmongo/lib/marshal/mapping.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/sfregexp/regexp.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  tests/output-snapshots/test-api-import.golden.txt
Labels: enhancement

#221 fix: Changement de structure des logs de parseurs
  dbmongo/lib/apconso/testData/expectedApconso.json
  dbmongo/lib/apdemande/testData/expectedApdemande.json
  dbmongo/lib/bdf/testData/expectedBdfOutput.json
  dbmongo/lib/diane/testData/expectedDiane.json
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/engine/event.go
  dbmongo/lib/marshal/event.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/reporder/testData/expectedReporder.json
  dbmongo/lib/sirene/testData/expectedSirene.json
  dbmongo/lib/sirene_ul/testData/expectedSireneUL.json
  dbmongo/lib/urssaf/testData/expectedCcsf.json
  dbmongo/lib/urssaf/testData/expectedCotisation.json
  dbmongo/lib/urssaf/testData/expectedDebit.json
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  dbmongo/lib/urssaf/testData/expectedDelai.json
  dbmongo/lib/urssaf/testData/expectedEffectif.json
  dbmongo/lib/urssaf/testData/expectedEffectifEnt.json
  dbmongo/lib/urssaf/testData/expectedProcol.json
  tests/output-snapshots/test-api-check.golden.txt
  tests/output-snapshots/test-api-import.golden.txt
  tests/test-api-check.sh
  tests/test-api-import.sh
Labels: enhancement

#224 fix(filter): Filtrage SIREN appliqué automatiquement à tous les parseurs
  dbmongo/lib/bdf/main.go
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/marshal/mapping_test.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
Labels: enhancement
