Repository signaux-faibles/opensignauxfaibles, pull requests merged in 2020-09, with the labels that each got.

#145 fix: Simplification de effectifs.ts (reduce.algo2) + améliorations Go
  dbmongo/data.go
  dbmongo/handlers.go
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/lib/engine/data.go
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#150 fix(deps): Mise à jour des dépendances JS/TS
  dbmongo/js/package-lock.json
  dbmongo/js/package.json
Labels: dependencies

#147 fix(tests): Composition simplifiée de scripts Mongo shell
  tests/helpers/populate-from-objects.sh
  tests/test-api-export.sh
  tests/test-api-reduce-2.sh
Labels: enhancement

#143 feat: API de validation des données par MongoDB / JSON Schema
  .github/workflows/e2e.yml
  dbmongo/data.go
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
  dbmongo/js/GeneratedTypes.d.ts
  dbmongo/js/generate-types.sh
  dbmongo/js/package-lock.json
  dbmongo/js/package.json
  dbmongo/lib/engine/data.go
  dbmongo/lib/engine/data_validation.go
  dbmongo/lib/engine/js/loadJS.go
  dbmongo/lib/engine/typescript.go
  dbmongo/main.go
  dbmongo/validation/README.md
  dbmongo/validation/bdf.schema.json
  dbmongo/validation/delai.schema.json
  dbmongo/validation/flatten_RawData.pipeline.json
  test-all.sh
  tests/input-data/RawData.validation.json
  tests/output-snapshots/test-api-validate.golden.json
  tests/test-api-validate.sh
Labels: enhancement

#146 fix(TS): Nommage systématique des fonctions importées
  dbmongo/js/compact/finalize.ts
  dbmongo/js/compact/reduce.ts
  dbmongo/js/public/apconso.ts
  dbmongo/js/public/apdemande.ts
  dbmongo/js/public/bdf.ts
  dbmongo/js/public/compte.ts
  dbmongo/js/public/delai.ts
  dbmongo/js/public/diane.ts
  dbmongo/js/public/effectifs.ts
  dbmongo/js/reduce.algo2/apart.ts
  dbmongo/js/reduce.algo2/cibleApprentissage.ts
  dbmongo/js/reduce.algo2/defaillances.ts
  dbmongo/js/reduce.algo2/delais.ts
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/js/reduce.algo2/entr_sirene.ts
  dbmongo/js/reduce.algo2/finalize.ts
  dbmongo/js/reduce.algo2/interim.ts
  dbmongo/js/reduce.algo2/sirene.ts
  dbmongo/lib/engine/js/loadJS.go
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#152 fix(compact): Utilisation de l'objet "f" pour l'appel de fonctions auxiliaires
  dbmongo/js/compact/applyPatchesToBatch.ts
  dbmongo/js/compact/applyPatchesToMemory.ts
  dbmongo/js/compact/compactBatch.ts
  dbmongo/js/compact/currentState.ts
  dbmongo/js/compact/fixRedundantPatches.ts
  dbmongo/js/compact/listHashesToAddAndDelete.ts
  dbmongo/js/compact/reduce.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: bug

#153 tests(reduce.algo2): Écriture de tests unitaires pour `effectifs.ts`
  dbmongo/js/RawDataTypes.ts
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/js/reduce.algo2/effectifs_tests.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#154 fix(compact): Ajout d'un test pour régression corrigée dans PR #152.
  .github/workflows/e2e.yml
  .gitignore
  .gitsecret/paths/mapping.cfg
  test-all.sh
  tests/output-snapshots/test-api-compact.golden.json.secret
  tests/test-api-compact.sh
Labels: bug

#155 fix(TS): Importation de `f` depuis un fichier par traitement
  dbmongo/js/compact/applyPatchesToBatch.ts
  dbmongo/js/compact/applyPatchesToMemory.ts
  dbmongo/js/compact/compactBatch.ts
  dbmongo/js/compact/currentState.ts
  dbmongo/js/compact/finalize.ts
  dbmongo/js/compact/fixRedundantPatches.ts
  dbmongo/js/compact/functions.ts
  dbmongo/js/compact/listHashesToAddAndDelete.ts
  dbmongo/js/compact/reduce.ts
  dbmongo/js/globalize-functions.sh
  dbmongo/js/public/apconso.ts
  dbmongo/js/public/apdemande.ts
  dbmongo/js/public/bdf.ts
  dbmongo/js/public/compte.ts
  dbmongo/js/public/cotisations.ts
  dbmongo/js/public/dealWithProcols.ts
  dbmongo/js/public/debits.ts
  dbmongo/js/public/delai.ts
  dbmongo/js/public/diane.ts
  dbmongo/js/public/effectifs.ts
  dbmongo/js/public/functions.ts
  dbmongo/js/public/map.ts
  dbmongo/js/reduce.algo2/apart.ts
  dbmongo/js/reduce.algo2/cibleApprentissage.ts
  dbmongo/js/reduce.algo2/cotisation.ts
  dbmongo/js/reduce.algo2/cotisationsdettes.ts
  dbmongo/js/reduce.algo2/dealWithProcols.ts
  dbmongo/js/reduce.algo2/defaillances.ts
  dbmongo/js/reduce.algo2/delais.ts
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/js/reduce.algo2/entr_bdf.ts
  dbmongo/js/reduce.algo2/entr_diane.ts
  dbmongo/js/reduce.algo2/entr_sirene.ts
  dbmongo/js/reduce.algo2/finalize.ts
  dbmongo/js/reduce.algo2/functions.ts
  dbmongo/js/reduce.algo2/interim.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/sirene.ts
  dbmongo/lib/engine/js/loadJS.go
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#156 feat(validation): Validation des données importées
  .github/workflows/e2e.yml
  dbmongo/data.go
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
  dbmongo/js/GeneratedTypes.d.ts
  dbmongo/lib/engine/data.go
  dbmongo/lib/engine/data_validation.go
  dbmongo/validation/bdf.schema.json
  dbmongo/validation/delai.schema.json
  dbmongo/validation/flatten_data_entries.pipeline.json
  test-all.sh
  tests/output-snapshots/test-api-import.golden.txt
  tests/test-api-import.sh
  tests/test-api-validate.sh
Labels: enhancement

#157 fix(import): Les erreurs de filtrage de Delai ne sont pas fatales
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
  dbmongo/handlers.go
  dbmongo/lib/engine/main.go
  dbmongo/lib/urssaf/delai.go
  tests/output-snapshots/test-api-import.golden.txt
  tests/test-api-import.sh
Labels: bug

#161 fix(logs): Complétion et correction des rapports de parseurs
  dbmongo/lib/altares/main.go
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apdemande/main.go
  dbmongo/lib/bdf/main.go
  dbmongo/lib/crp/main.go
  dbmongo/lib/diane/main.go
  dbmongo/lib/engine/main.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/compte.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/delai.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/procol.go
  tests/output-snapshots/test-api-import.golden.txt
Labels: enhancement

#159 clean(import): 🧹 Suppression des générateurs de parseurs (inutilisés)
  dbmongo/handlers.go
  dbmongo/lib/engine/errors.go
  dbmongo/lib/marshal/generateParser.go
  dbmongo/lib/marshal/helperParsingFunctions.go
  dbmongo/lib/marshal/helperParsingFunctions_test.go
  dbmongo/lib/marshal/marshal.go
  dbmongo/lib/marshal/marshal_test.go
  dbmongo/lib/marshal/parse.go
  dbmongo/lib/marshal/parse_test.go
  dbmongo/lib/marshal/parserSpecs/apconso.yaml
  dbmongo/lib/marshal/parserSpecs/apdemande.yaml
  dbmongo/lib/marshal/parserSpecs/comptes.yaml
  dbmongo/lib/marshal/parserSpecs/debit.yaml
  dbmongo/lib/marshal/parserSpecs/reporder.yaml
  dbmongo/lib/marshal/parserSpecs/sirene.yaml
  dbmongo/lib/marshal/readOptions.go
  dbmongo/lib/marshal/readOptions_test.go
  dbmongo/lib/marshal/testData/test1_ParserOptions.yaml
  dbmongo/lib/marshal/testData/test1_md5.csv
  dbmongo/lib/marshal/testData/test2_ParserOptions.yaml
  dbmongo/lib/marshal/testData/test2_md5.csv
  dbmongo/lib/marshal/testData/test3_ParserOptions.yaml
  dbmongo/lib/marshal/testData/test4_ParserOptions.yaml
  dbmongo/lib/marshal/testData/test5_ParserOptions.yaml
  dbmongo/lib/marshal/testData/testParserOptions/wrong_format.youml
  dbmongo/lib/urssaf/delai.go
Labels: enhancement

#160 fix(TS): Transpilation plus rapide + invocation plus simple
  dbmongo/js/generate-javascript.sh
  dbmongo/js/generate-types.sh
  dbmongo/lib/engine/js/loadJS.go
  dbmongo/lib/engine/typescript.go
Labels: enhancement

#165 fix(build): Go generate rafraîchit les définitions Swagger
  dbmongo/docs/convert-yaml-to-json.sh
  dbmongo/docs/docs.go
  dbmongo/docs/index.go
  dbmongo/docs/load.go
  dbmongo/docs/swagger/build.go
  dbmongo/docs/swagger/convert-yaml-to-json.sh
  tests/test-api-swagger.sh
Labels: enhancement

#171 test(import): "Import devrait échouer en tentant d'ouvrir un fichier illisible"
  dbmongo/lib/engine/adminBatch_test.go
Labels: enhancement

#172 fix(bdf): filtrage des siren dans le parser d'import bdf
  dbmongo/lib/bdf/main.go
  dbmongo/lib/bdf/main_test.go
  dbmongo/lib/bdf/testData/bdfTestData.csv
  dbmongo/lib/bdf/testData/expectedBdf.json
Labels: enhancement

#173 fix: Renforcement du parseur Bdf (avant de s'intéresser aux autres)
  dbmongo/lib/base/errors.go
  dbmongo/lib/bdf/main.go
  dbmongo/lib/bdf/main_test.go
  dbmongo/lib/bdf/testData/expectedBdf.json
  dbmongo/lib/bdf/testData/expectedBdfOutput.json
  dbmongo/lib/engine/main_test.go
  dbmongo/lib/marshal/testing.go
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  tests/output-snapshots/test-api-import.golden.txt
Labels: bug, enhancement

#174 refactor(BDF): Encapsulation de la partie pure du parseur BDF
  dbmongo/lib/bdf/main.go
Labels: enhancement

#170 fix(urssaf): Tolérance aux lignes CSV corrompues
  .github/workflows/e2e.yml
  dbmongo/docs/load.go
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
  dbmongo/lib/base/errors.go
  dbmongo/lib/marshal/testing.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/testData/debitCorrompuTestData.csv
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  dbmongo/lib/urssaf/urssaf_test.go
  test-all.sh
  tests/output-snapshots/test-api-check.golden.txt
  tests/test-api-check.sh
Labels: enhancement
