Repository signaux-faibles/opensignauxfaibles, pull requests merged in 2020-11, with the labels that each got.

#227 fix(tests): MAJ golden file de test-api-import
  tests/output-snapshots/test-api-import.golden.txt
Labels: bug

#228 Hotfix/parser compute valid lines
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/sirene/testData/expectedSirene.json
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  tests/output-snapshots/test-api-check.golden.txt
  tests/output-snapshots/test-api-import.golden.txt
Labels: enhancement

#225 fix(parsers): Itération de parsing pilotée par runParserWithSirenFilter()
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apconso/testData/expectedApconso.json
  dbmongo/lib/apdemande/main.go
  dbmongo/lib/apdemande/testData/expectedApdemande.json
  dbmongo/lib/base/errors.go
  dbmongo/lib/bdf/main.go
  dbmongo/lib/bdf/main_test.go
  dbmongo/lib/bdf/testData/expectedBdfOutput.json
  dbmongo/lib/diane/main.go
  dbmongo/lib/diane/testData/expectedDiane.json
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/ellisphere/main_test.go
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/marshal/mapping.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/reporder/testData/expectedReporder.json
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene/testData/expectedSirene.json
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/sirene_ul/testData/expectedSireneUL.json
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/compte.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/delai.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/procol.go
  dbmongo/lib/urssaf/testData/expectedCcsf.json
  dbmongo/lib/urssaf/testData/expectedCotisation.json
  dbmongo/lib/urssaf/testData/expectedDebit.json
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  dbmongo/lib/urssaf/testData/expectedDelai.json
  dbmongo/lib/urssaf/testData/expectedEffectif.json
  dbmongo/lib/urssaf/testData/expectedEffectifEnt.json
  dbmongo/lib/urssaf/testData/expectedProcol.json
  dbmongo/lib/urssaf/urssaf_test.go
  test-all.sh
  tests/output-snapshots/test-api-check.golden.txt
  tests/output-snapshots/test-api-import.golden.txt
Labels: bug, enhancement

#231 fix(parseurs): Chaque parseur implémente l'interface Parser
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apdemande/main.go
  dbmongo/lib/bdf/main.go
  dbmongo/lib/diane/main.go
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/marshal/testing.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/compte.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/delai.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/procol.go
Labels: enhancement

#232 fix(parseurs): Imposer la qualification de chaque erreur de parsing
  dbmongo/lib/apconso/main.go
  dbmongo/lib/apdemande/main.go
  dbmongo/lib/base/errors.go
  dbmongo/lib/bdf/main.go
  dbmongo/lib/diane/main.go
  dbmongo/lib/ellisphere/main.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/reporder/reporder.go
  dbmongo/lib/sirene/main.go
  dbmongo/lib/sirene_ul/main.go
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/compte.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/delai.go
  dbmongo/lib/urssaf/effectif.go
  dbmongo/lib/urssaf/effectif_ent.go
  dbmongo/lib/urssaf/procol.go
Labels: enhancement

#229 feat(journal): Garder une trace de l'API qui a produit chaque rapport
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/event.go
  dbmongo/lib/marshal/event.go
  tests/output-snapshots/test-api-check.golden.txt
  tests/output-snapshots/test-api-import.golden.txt
  tests/test-api-check.sh
  tests/test-api-import.sh
Labels: enhancement

#235 fix: correction d'un bug dans le traitement des procédures collectives
  dbmongo/js/RawDataTypes.ts
  dbmongo/js/reduce.algo2/dealWithProcols.ts
  dbmongo/js/reduce.algo2/dealWithProcols_tests.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: bug

#236 fix(#234): Le binaire ne doit pas nécessiter la présence de fichiers JSON
  .github/workflows/e2e.yml
  dbmongo/lib/engine/data_validation.go
  dbmongo/lib/engine/js/loadJS.go
  dbmongo/lib/engine/jsFunctions.go
  dbmongo/lib/engine/reduce.go
  dbmongo/lib/engine/validation/bundle-schemas.go
  dbmongo/lib/engine/validationSchemas.go
Labels: bug

#238 fix(#234): dbmongo doit pouvoir s'exécuter en l'absence du code source
  .github/workflows/e2e.yml
  .github/workflows/go.yml
  dbmongo/config-sample.toml
  dbmongo/lib/diane/convert_diane.sh
  dbmongo/lib/diane/main.go
  dbmongo/lib/diane/main_test.go
  dbmongo/lib/diane/testData/dianeTestData.txt
Labels: bug

#240 fix(parsing): Réduction d'empreinte mémoire lors du parsing de lignes filtrées
  dbmongo/lib/apconso/testData/expectedApconso.json
  dbmongo/lib/apdemande/testData/expectedApdemande.json
  dbmongo/lib/base/errors.go
  dbmongo/lib/bdf/testData/expectedBdfOutput.json
  dbmongo/lib/diane/testData/expectedDiane.json
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/marshal/mapping_test.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/reporder/testData/expectedReporder.json
  dbmongo/lib/sirene/testData/expectedSirene.json
  dbmongo/lib/sirene_ul/testData/expectedSireneUL.json
  dbmongo/lib/urssaf/testData/expectedCcsf.json
  dbmongo/lib/urssaf/testData/expectedCotisation.json
  dbmongo/lib/urssaf/testData/expectedDebit.json
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  dbmongo/lib/urssaf/testData/expectedDelai.json
  dbmongo/lib/urssaf/testData/expectedEffectif.json
  dbmongo/lib/urssaf/testData/expectedEffectifEnt.json
  dbmongo/lib/urssaf/testData/expectedProcol.json
  dbmongo/lib/urssaf/urssaf_test.go
  tests/output-snapshots/test-api-check.golden.txt
  tests/output-snapshots/test-api-import.golden.txt
  tests/test-api-check.sh
  tests/test-api-import.sh
Labels: enhancement

#241 feat(api): Suppression des routes API qui ne sont plus utilisées
  dbmongo/browse.go
  dbmongo/data.go
  dbmongo/docs/load.go
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
  dbmongo/go.mod
  dbmongo/handlers.go
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/adminBatch_test.go
  dbmongo/lib/engine/browse.go
  dbmongo/lib/engine/data.go
  dbmongo/lib/engine/event.go
  dbmongo/lib/engine/public.go
  dbmongo/lib/engine/reduce.go
  dbmongo/lib/engine/type.go
  dbmongo/lib/files/main.go
  dbmongo/main.go
Labels: enhancement

#245 feat(api): Comptage et suppression d'entités qui auraient du être filtrées
  .github/workflows/e2e.yml
  dbmongo/handlers.go
  dbmongo/lib/engine/data.go
  dbmongo/main.go
  test-all.sh
  tests/test-api-prune-entities.sh
Labels: enhancement

#244 fix: Économiser la mémoire de stockage d'erreurs de parsing
  dbmongo/go.mod
  dbmongo/go.sum
  dbmongo/lib/base/errors.go
  dbmongo/lib/ellisphere/testData/expectedEllisphere.json
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/sirene/testData/expectedSirene.json
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json
  tests/output-snapshots/test-api-check.golden.txt
  tests/output-snapshots/test-api-import.golden.txt
Labels: bug

#246 fix(parsing): Réduire l'usage mémoire des erreurs de parsing – 2ème partie
  dbmongo/lib/base/errors.go
  dbmongo/lib/marshal/mapping.go
  dbmongo/lib/marshal/parser.go
  dbmongo/lib/marshal/tracker.go
  dbmongo/lib/marshal/tracker_test.go
  dbmongo/lib/urssaf/ccsf.go
  dbmongo/lib/urssaf/cotisation.go
  dbmongo/lib/urssaf/debit.go
  dbmongo/lib/urssaf/delai.go
Labels: enhancement

#243 fix: l'API reduce ne supporte plus que algo2
  .gitsecret/paths/mapping.cfg
  dbmongo/data.go
  dbmongo/js/RawDataTypes.ts
  dbmongo/js/compact/ava_tests.ts
  dbmongo/js/compact/finalize.ts
  dbmongo/js/compact/finalize_tests.ts
  dbmongo/js/public/ava_tests.ts
  dbmongo/js/reduce.algo2/ava_tests.ts
  dbmongo/js/test/data/objects.js
  dbmongo/lib/engine/adminBatch.go
  dbmongo/lib/engine/jsFunctions.go
  dbmongo/lib/engine/reduce.go
  tests/input-data/RawData.validation.json
  tests/output-snapshots/test-api-compact.golden.json.secret
  tests/output-snapshots/test-api.golden.txt
  tests/test-api-reduce-2.sh
  tests/test-api-reduce.sh
  tests/test-api.sh
Labels: enhancement

#247 docs(api): Ajout de /pruneEntities dans la définition Swagger
  dbmongo/docs/load.go
  dbmongo/docs/swagger/swagger.json
  dbmongo/docs/swagger/swagger.yaml
Labels: enhancement
