Repository signaux-faibles/opensignauxfaibles, pull requests merged in 2020-07, with the labels that each got.

#84 fix(TS): Déclaration des paramètres au lieu de globales
  dbmongo/js/compact/compactBatch.ts
  dbmongo/js/compact/complete_reporder.ts
  dbmongo/js/compact/reduce.ts
  dbmongo/js/globals.ts
  dbmongo/js/reduce.algo2/cotisationsdettes.ts
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/populateNafAndApe.ts
Labels: enhancement

#86 fix(TS): Renommage de BatchDataType en DataType
  dbmongo/js/compact/applyPatchesToBatch.ts
  dbmongo/js/compact/applyPatchesToMemory.ts
  dbmongo/js/compact/compactBatch.ts
  dbmongo/js/compact/fixRedundantPatches.ts
  dbmongo/js/compact/listHashesToAddAndDelete.ts
  dbmongo/js/globals.ts
  dbmongo/js/reduce.algo2/flatten.ts
Labels: enhancement

#89 fix(TS): Erreur d'importation de Ava rapportée par IDE
  dbmongo/js/tsconfig.json
Labels: enhancement

#88 fix(algo2): Passage des délais en jours
  dbmongo/js/globals.ts
  dbmongo/js/reduce.algo2/delais.ts
  dbmongo/js/reduce.algo2/delais_tests.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/nbDays.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#90 fix(compact): Renommage paramètre batch / batchKey --> fromBatchKey
  dbmongo/data.go
  dbmongo/js/compact/ava_tests.ts
  dbmongo/js/compact/compactBatch.ts
  dbmongo/js/compact/reduce.ts
  dbmongo/js/compact/reduce_test.js
  dbmongo/lib/engine/data.go
  dbmongo/lib/engine/jsFunctions.go
  test-api.sh
Labels: enhancement

#91 tests(TS): Réécriture du des tests de `compact` en TypeScript/AVA
  dbmongo/js/compact/currentState_test.js
  dbmongo/js/compact/currentState_tests.ts
  dbmongo/js/compact/finalize_test.js
  dbmongo/js/compact/finalize_tests.ts
  dbmongo/js/compact/reduce_tests.ts
  dbmongo/js/test/helpers/testing.js
  dbmongo/js/test/test_compact.sh
Labels: enhancement

#92 tests(TS): Réécriture du des tests de `reduce.algo2` en TypeScript/AVA
  dbmongo/js/reduce.algo2/_test.js
  dbmongo/js/reduce.algo2/add.ts
  dbmongo/js/reduce.algo2/add_test.js
  dbmongo/js/reduce.algo2/add_tests.ts
  dbmongo/js/reduce.algo2/algo2_tests.ts
  dbmongo/js/reduce.algo2/cibleApprentissage.ts
  dbmongo/js/reduce.algo2/cibleApprentissage_test.js
  dbmongo/js/reduce.algo2/cibleApprentissage_tests.ts
  dbmongo/js/reduce.algo2/lookAhead.ts
  dbmongo/js/reduce.algo2/lookAhead_test.js
  dbmongo/js/reduce.algo2/lookAhead_tests.ts
  dbmongo/js/reduce.algo2/map_tests.ts
  dbmongo/js/test/data/naf.d.ts
  dbmongo/js/test/data/naf.js
  dbmongo/js/test/data/objects.d.ts
  dbmongo/js/test/data/objects.js
  dbmongo/js/test/helpers/fake_emit_for_algo2.js
  dbmongo/js/test/helpers/fakes.js
  dbmongo/js/test/helpers/reducers.d.ts
  dbmongo/js/test/helpers/reducers.js
  dbmongo/js/test/helpers/testing.js
  dbmongo/js/test/test_algo2.sh
  dbmongo/js/test/test_public.sh
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#93 fix(reduce.algo2): Calcul des montants de cotisations avant appel à delais()
  dbmongo/js/reduce.algo2/cotisationsdettes.ts
  dbmongo/js/reduce.algo2/delais.ts
  dbmongo/js/reduce.algo2/delais_tests.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/outputs.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#94 fix(reduce.algo2): Retrait de `montant_majorations`, affinage de types et autres améliorations
  dbmongo/js/common/compareDebit.ts
  dbmongo/js/globals.ts
  dbmongo/js/public/compareDebit.js
  dbmongo/js/reduce.algo2/cotisationsdettes.ts
  dbmongo/js/reduce.algo2/cotisationsdettes_tests.ts
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/outputs.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#95 tests(reduce.algo2): Test de non régression sur calcul de delai_deviation_remboursement
  dbmongo/js/globals.ts
  dbmongo/js/reduce.algo2/algo2_tests.ts
  dbmongo/js/reduce.algo2/flatten.ts
  dbmongo/js/reduce.algo2/map.ts
Labels: enhancement

#97 fix(tests): Rendre les erreurs d'API plus visibles
  test-api-2.sh
  test-api.sh
Labels: enhancement

#96 fix(reduce.algo2): Suite du refactoring de cotisationsdette + simplification des tris
  dbmongo/js/globals.ts
  dbmongo/js/reduce.algo2/apart.ts
  dbmongo/js/reduce.algo2/cotisation.ts
  dbmongo/js/reduce.algo2/cotisationsdettes.ts
  dbmongo/js/reduce.algo2/cotisationsdettes_tests.ts
  dbmongo/js/reduce.algo2/dealWithProcols.ts
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/js/reduce.algo2/lookAhead.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#99 tests(dettes): Réécriture du jeu de tests sous forme de tableau
  dbmongo/js/reduce.algo2/cotisationsdettes_tests.ts
Labels: enhancement

#98 fix(tests): Mise à jour de golden master + nettoyage code & logs
  test-api-2.sh
  test-api.sh
Labels: enhancement

#100 fix(reduce.algo2): Renommage et explicitation des types dans effectifs()
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#101 fix(reduce.algo2): Extraction de entr_bdf()
  dbmongo/js/common/omit.ts
  dbmongo/js/globals.ts
  dbmongo/js/reduce.algo2/cotisationsdettes_tests.ts
  dbmongo/js/reduce.algo2/entr_bdf.ts
  dbmongo/js/reduce.algo2/entr_sirene.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#102 fix(reduce.algo2): Simplification de la signature de entr_sirene()
  dbmongo/js/reduce.algo2/entr_sirene.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#103 tests(reduce.algo2): Test de non régression de map() avec données BdF
  dbmongo/js/reduce.algo2/map_tests.ts
  dbmongo/js/reduce.algo2/map_tests.ts.md
  dbmongo/js/reduce.algo2/map_tests.ts.snap
Labels: bug

#106 fix(TS): Conversion des derniers tests JS de reduce.algo2 en TypeScript
  .github/workflows/go.yml
  .github/workflows/js-functions.yml
  dbmongo/js/compact/ava_tests.ts
  dbmongo/js/compact/map.ts
  dbmongo/js/globals.ts
  dbmongo/js/public/_test.js
  dbmongo/js/public/ava_tests.ts
  dbmongo/js/reduce.algo2/algo2_golden_tests.ts
  dbmongo/js/reduce.algo2/algo2_tests.ts
  dbmongo/js/reduce.algo2/ava_tests.ts
  dbmongo/js/reduce.algo2/finalize_test.js
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/map_test.js
  dbmongo/js/reduce.algo2/map_tests.ts
  dbmongo/js/reduce.algo2/outputs.ts
  dbmongo/js/reduce.algo2/reduce.ts
  dbmongo/js/test/helpers/fakes.js
  dbmongo/js/test/helpers/mongodb.ts
  dbmongo/js/test/helpers/test_env_for_public.js
  dbmongo/js/test/test_finalize_algo2.sh
  dbmongo/js/test/test_map_algo2.sh
  dbmongo/js/test/test_public.sh
  dbmongo/js/tsconfig-transpilation.json
  dbmongo/js/tsconfig.json
  dbmongo/js_test.go
  dbmongo/lib/engine/js/loadJS.go
  dbmongo/lib/engine/jsFunctions.go
  dbmongo/lib/engine/typescript.go
  test-all.sh
Labels: enhancement

#107 fix(reduce.algo2): Réécriture de cotisation() + autres `TODO`s
  dbmongo/js/common/omit.ts
  dbmongo/js/compact/currentState_tests.ts
  dbmongo/js/compact/reduce_tests.ts
  dbmongo/js/globals.ts
  dbmongo/js/package.json
  dbmongo/js/reduce.algo2/algo2_golden_tests.ts
  dbmongo/js/reduce.algo2/compte.ts
  dbmongo/js/reduce.algo2/cotisation.ts
  dbmongo/js/reduce.algo2/delais_tests.ts
  dbmongo/js/reduce.algo2/interim.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/reduce.algo2/map_tests.ts.snap
  dbmongo/lib/engine/jsFunctions.go
Labels: bug, enhancement

#111 fix(deps): Mise à jour de Node.js et dépendances
  dbmongo/js/.nvmrc
  dbmongo/js/package-lock.json
  dbmongo/js/package.json
Labels: enhancement

#112 fix: Tests avec sudo docker (par défaut sous linux)
  test-all.sh
  test-api-2.sh
  test-api-reduce.sh
  test-api.sh
Labels: bug

#110 fix(reduce.algo2): Correction de la prise en compte des valeurs manquantes dans les calculs de moyennes
  dbmongo/js/reduce.algo2/algo2_golden_tests.ts
  dbmongo/js/reduce.algo2/ava_tests.ts
  dbmongo/js/reduce.algo2/cotisation.ts
  dbmongo/js/reduce.algo2/cotisation_tests.ts
  dbmongo/lib/engine/jsFunctions.go
  test-api-2.sh
  test-api.golden-master.txt
Labels: bug

#109 fix(reduce.algo2): Extraction de entr_diane(), hors de map()
  dbmongo/js/reduce.algo2/entr_diane.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/lib/engine/jsFunctions.go
Labels: enhancement

#113 fix(CI): Exécution de *tous* les tests en Intégration Continue
  .github/workflows/e2e.yml
  .github/workflows/js-functions.yml
  .gitignore
  .gitsecret/keys/pubring.kbx
  .gitsecret/keys/trustdb.gpg
  .gitsecret/paths/mapping.cfg
  README.md
  dbmongo/js/reduce.algo2/algo2_golden_tests.ts
  test-api-2.sh
  test-api-2_golden.json.secret
  test-api-reduce.sh
  test-api.sh
  test-reduce-data.json.secret
  test-reduce-finalize_golden.json.secret
  test-reduce-map_golden.json.secret
Labels: enhancement

#108 Fix(public): Conversion TypeScript de test_public.sh + _test.js
  .github/workflows/go.yml
  .github/workflows/js-functions.yml
  dbmongo/js/common/dateAddMonth.ts
  dbmongo/js/common/procolToHuman.ts
  dbmongo/js/globals.ts
  dbmongo/js/public/_test.js
  dbmongo/js/public/bdf.js
  dbmongo/js/public/bdf.ts
  dbmongo/js/public/dateAddDay.js
  dbmongo/js/public/dateAddDay.ts
  dbmongo/js/public/dateAddMonth.js
  dbmongo/js/public/diane.js
  dbmongo/js/public/diane.ts
  dbmongo/js/public/procolToHuman.js
  dbmongo/js/public/public_tests.ts
  dbmongo/js/reduce.algo2/algo2_golden_tests.ts
  dbmongo/js/reduce.algo2/ava_tests.ts
  dbmongo/js/reduce.algo2/cotisation.ts
  dbmongo/js/reduce.algo2/cotisation_tests.ts
  dbmongo/js/reduce.algo2/cotisationsdettes.ts
  dbmongo/js/reduce.algo2/cotisationsdettes_tests.ts
  dbmongo/js/reduce.algo2/dealWithProcols.ts
  dbmongo/js/reduce.algo2/effectifs.ts
  dbmongo/js/reduce.algo2/entr_bdf.ts
  dbmongo/js/reduce.algo2/entr_diane.ts
  dbmongo/js/reduce.algo2/interim.ts
  dbmongo/js/reduce.algo2/map.ts
  dbmongo/js/test/data/objects.d.ts
  dbmongo/js/test/helpers/test_env_for_public.js
  dbmongo/js/test/test_public.sh
  dbmongo/js_test.go
  dbmongo/lib/engine/js/loadJS.go
  dbmongo/lib/engine/jsFunctions.go
  dbmongo/lib/engine/typescript.go
  test-all.sh
Labels: enhancement

#114 fix(reduce.algo2): Correction du calcul de ratio de dette moyenne sur 12 mois
  .gitsecret/paths/mapping.cfg
  dbmongo/js/package.json
  dbmongo/js/reduce.algo2/ava_tests.ts
  dbmongo/js/reduce.algo2/cotisation.ts
  dbmongo/js/reduce.algo2/cotisation_tests.ts
  dbmongo/js/reduce.algo2/map_tests.ts.md
  dbmongo/js/reduce.algo2/map_tests.ts.snap
  dbmongo/lib/engine/jsFunctions.go
  test-api-2.sh
  test-api-2_golden.json.secret
  test-api-reduce.golden-master.json
  test-api.golden-master.txt
  test-reduce-data.json.secret
  test-reduce-finalize_golden.json.secret
  test-reduce-map_golden.json.secret
Labels: bug
