Repository signaux-faibles/opensignauxfaibles, pull requests merged in 2021-03, with the labels that each got.

#324 fix(TS): Indexation temporelle des données à l'aide de Map
  js/RawDataTypes.ts
  js/common/makePeriodeMap.ts
  js/public/effectifs.ts
  js/public/functions.ts
  js/reduce.algo2/add.ts
  js/reduce.algo2/add_tests.ts
  js/reduce.algo2/apart.ts
  js/reduce.algo2/cibleApprentissage.ts
  js/reduce.algo2/compte.ts
  js/reduce.algo2/cotisation.ts
  js/reduce.algo2/cotisation_tests.ts
  js/reduce.algo2/cotisationsdettes.ts
  js/reduce.algo2/cotisationsdettes_tests.ts
  js/reduce.algo2/defaillances.ts
  js/reduce.algo2/defaillances_tests.ts
  js/reduce.algo2/delais.ts
  js/reduce.algo2/delais_tests.ts
  js/reduce.algo2/effectifs.ts
  js/reduce.algo2/effectifs_tests.ts
  js/reduce.algo2/entr_bdf.ts
  js/reduce.algo2/entr_diane.ts
  js/reduce.algo2/entr_paydex.ts
  js/reduce.algo2/entr_paydex_tests.ts
  js/reduce.algo2/entr_sirene.ts
  js/reduce.algo2/functions.ts
  js/reduce.algo2/lookAhead.ts
  js/reduce.algo2/lookAhead_tests.ts
  js/reduce.algo2/map.ts
  js/reduce.algo2/outputs.ts
  js/reduce.algo2/populateNafAndApe.ts
  js/reduce.algo2/repeatable.ts
  js/test/helpers/parPeriode.ts
  lib/engine/jsFunctions.go
  test-all.sh
Labels: enhancement

#326 feat(reduce.algo2): Ajout de variables temporelles Paydex
  js/reduce.algo2/algo2_tests.ts.md
  js/reduce.algo2/algo2_tests.ts.snap
  js/reduce.algo2/docs/variables.json
  js/reduce.algo2/entr_paydex.ts
  js/reduce.algo2/entr_paydex_tests.ts
  lib/engine/jsFunctions.go
Labels: enhancement

#327 fix(tests): `test-all.sh --update` met à jour aussi les snapshots ava
  test-all.sh
Labels: enhancement

#329 fix(check): Récupérer le rapport pour tous les fichiers parsés
  lib/engine/adminBatch.go
  lib/engine/event.go
  tests/output-snapshots/test-check.golden.txt
  tests/test-check.sh
Labels: bug

#330 fix(reduce): Génération plus rapide de la collection Features
  lib/engine/reduce.go
Labels: enhancement

#334 fix(Makefile): Permettre la cross-compilation (CGO_ENABLED=0)
  Makefile
  tests/output-snapshots/test-check.golden.txt
Labels: bug

#336 fix(tests): Figer l'ordre des rapports de `sfdata check`
  handlers.go
  tests/output-snapshots/test-check.golden.txt
  tests/test-check.sh
Labels: bug

#337 fix(CI): Validation du titre des PRs
  .github/semantic.yml
Labels: enhancement, low priority

#331 fix(TS): Sécurisation des types indexés par des chaines de caractères
  js/compact/ava_tests.ts
  js/compact/currentState.ts
  js/public/ava_tests.ts
  js/public/bdf.ts
  js/public/diane.ts
  lib/engine/jsFunctions.go
Labels: enhancement

#335 docs(urssaf): Documentation des champs CCSF importés
  .gitsecret/paths/mapping.cfg
  js/GeneratedTypes.d.ts
  lib/engine/validationSchemas.go
  lib/urssaf/testData/ccsfTestData.csv
  lib/urssaf/testData/expectedCcsf.json
  tests/output-snapshots/reduce-map-output.golden.json.secret
  tests/output-snapshots/test-import.golden.txt
  validation/ccsf.schema.json
Labels: enhancement
